[build]
target = "avr-specs/avr-atmega32u4.json"

[target.'cfg(target_arch = "avr")']
#runner = "avrdude -v -p m32u4 -cavr109 -P COM20 -D -Uflash:w:target/avr-atmega32u4/debug/dot-matrix-badge.elf:e"
runner = "ravedude uno -cb 57600"

[unstable]
build-std = ["core"]
