[build]
target = "avr-specs/avr-atmega32u4.json"

[target.'cfg(target_arch = "avr")']
runner = "avrdude -v -p m32u4 -cavr109 -Uflash:w:target/avr-atmega32u4/debug/NONIK0.elf:e"
#runner = "ravedude uno -cb 57600"

[unstable]
build-std = ["core"]
